import React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { CamlFooterRenderer } from "../src/CamlFooter";

const meta: Meta<typeof CamlFooterRenderer> = {
  title: "CamlFooter",
  component: CamlFooterRenderer,
  parameters: {
    layout: "fullscreen",
  },
  argTypes: {
    footer: { control: "object" },
  },
};

export default meta;
type Story = StoryObj<typeof CamlFooterRenderer>;

export const WithNavigation: Story = {
  args: {
    footer: {
      nav: [
        { label: "Documentation", href: "https://docs.example.com" },
        { label: "GitHub", href: "https://github.com/example/opencontracts" },
        { label: "API Reference", href: "https://api.example.com/docs" },
        { label: "Support", href: "https://support.example.com" },
      ],
      notice:
        "Copyright 2024 OpenContracts. All rights reserved. This report is generated from automated contract analysis and should be reviewed by qualified legal counsel.",
    },
  },
};

export const NoticeOnly: Story = {
  args: {
    footer: {
      notice:
        "This document was generated by OpenContracts automated analysis pipeline. Content is provided for informational purposes only and does not constitute legal advice.",
    },
  },
};

export const NavigationOnly: Story = {
  args: {
    footer: {
      nav: [
        { label: "Terms of Service", href: "https://example.com/terms" },
        { label: "Privacy Policy", href: "https://example.com/privacy" },
        { label: "Contact", href: "https://example.com/contact" },
      ],
    },
  },
};
